# Generated by Django 3.2.4 on 2021-06-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='hire_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
