# Generated by Django 3.2.4 on 2021-06-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210628_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='profile_img',
            field=models.ImageField(upload_to='team/%Y/%m/%d'),
        ),
    ]
