# Generated by Django 3.2.4 on 2021-07-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquery',
            name='user_id',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
