# Generated by Django 3.2.4 on 2021-07-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_inquery_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquery',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
