# Generated by Django 3.2.4 on 2021-07-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_inquery_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquery',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
