# Generated by Django 3.2.4 on 2021-07-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_inquery_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquery',
            name='car_title',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
