# Generated by Django 3.2.4 on 2021-07-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='feature_img',
            field=models.ImageField(blank=True, upload_to='blog/{author}/'),
        ),
    ]
