# Generated by Django 3.2.4 on 2021-06-29 12:05

import ckeditor.fields
import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=100)),
                ('states', models.CharField(choices=[('P1', 'Provience No. 1'), ('P2', 'Provience No. 2'), ('BP', 'Bagamati Provience'), ('LP', 'Lumbini Provience'), ('KP', 'Karnali Provience'), ('SP', 'Sudurpaschim Provience')], max_length=100)),
                ('city', models.CharField(default='none', max_length=100)),
                ('years', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)])),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('ParkAssist', 'ParkAssist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Wind Deflector', 'Wind Deflector'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Automatic Headlights', 'Automatic Headlights')], max_length=216)),
                ('doors', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=100)),
                ('passenger', models.PositiveIntegerField()),
                ('model', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('milege', models.IntegerField()),
                ('miles', models.PositiveIntegerField()),
                ('description', ckeditor.fields.RichTextField()),
                ('interior', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('tumbnail_img', models.ImageField(upload_to='cars/%Y/%m/%d')),
                ('pic_front', models.ImageField(upload_to='cars/%Y/%m/%d')),
                ('pic_back', models.ImageField(upload_to='cars/%Y/%m/%d')),
                ('pic_left', models.ImageField(upload_to='cars/%Y/%m/%d')),
                ('pic_right', models.ImageField(upload_to='cars/%Y/%m/%d')),
                ('body_style', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('no_of_passed_owners', models.IntegerField()),
                ('transmission', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('vin_number', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
