# Generated by Django 3.2.4 on 2021-07-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
