# Generated by Django 3.2.4 on 2021-07-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='states',
            field=models.CharField(choices=[('Provience No.1', 'Provience No. 1'), ('Provience No.2 ', 'Provience No. 2'), ('Bagmati Provience', 'Bagamati Provience'), ('Lumbini Provience', 'Lumbini Provience'), ('Karnali Provience', 'Karnali Provience'), ('Sudarpashim Provience', 'Sudurpaschim Provience')], max_length=100),
        ),
    ]
